### ISSUE TITLE
The location of pets

### ISSUE THREAD

**Issue by Lin-Silver** [PYmili/MyFlowingFireflyWife#2]
How can I get the location of the desktop pet icon on the desktop?

**Comment by PYmili** [comment]
Sorry, I didn't understand the problem you mentioned. Please describe your problem in detail, and I will answer or repair it.

**Comment by Lin-Silver** [comment]
What I mean is, I want to know the real-time coordinates of this icon (firefly) on the desktop. I can’t get its position through the QWidget object name.

**Comment by PYmili** [comment]
I still don't understand your question. Your answer is too concise. There is no detailed picture or text description. I don't know what is needed. You said that you want to obtain the location of the icon on the desktop. You can view the pyqt document to obtain the location, usually using the 'pos()' method.

我还是不理解你说的问题，你的回答太过简洁，没有详细的图片或文字描述，我根本不知道需要什么。你说你想要获取 (firefly) 的 图标 在桌面的位置，获取位置你可以查看pyqt的文档，一般使用`pos()`方法。

**Comment by Lin-Silver** [comment]
Ok, thank you.That’s exactly what I mean.
I previously tried to use this method to get the location, but it failed:
        character_widget = self.findChild(QWidget, "character_widget")  # Assume the QWidget object for the character image of Liuying is named ‘character_widget’.
        if character_widget:
            character_x = character_widget.x()
            character_y = character_widget.y()
